
export const ADD_SOMETHING = "ADD_SOMETHING";
export const MODIFY_SOMETHING = "MODIFY_SOMETHING";
export const DELETE_SOMETHING = "DELETE_SOMETHING";

export const TELNET_REQUEST = "TELNET_REQUEST";
export const TELNET_REQUEST_SUCCEED = "TELNET_REQUEST_SUCCEED";
export const TELNET_REQUEST_FAILED = "TELNET_REQUEST_FAILED";