
export const ADD_SOMETHING = "ADD_SOMETHING";
export const MODIFY_SOMETHING = "MODIFY_SOMETHING";
export const DELETE_SOMETHING = "DELETE_SOMETHING";

export const TELNET_REQUEST = "TELNET_REQUEST";
export const TELNET_REQUEST_SUCCEED = "TELNET_REQUEST_SUCCEED";
export const TELNET_REQUEST_FAILED = "TELNET_REQUEST_FAILED";

export const RUN = "RUN";
export const STOP = "STOP";

export const SET_CLIENT = "SET_CLIENT";
export const SET_INTERVAL = "SET_INTERVAL";

export const SET_LOGIN = "SET_LOGIN";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_IP = "SET_IP";

export const SHOW_RAW = "SHOW_RAW";
export const SHOW_SNRCHARTS = "SHOW_SNRCHARTS";
export const SHOW_ATTCHARTS = "SHOW_ATTCHARTS";
export const SHOW_ERRORSCHARTS = "SHOW_ERRORSCHARTS";